### Validate, taht env variables are set
GET http://localhost:{{PORT}}

### Validate chat
POST http://localhost:{{PORT}}/chat
Content-Type: application/json

{
  "message": "What is quantum physics?",
  "maxTokenCount": 2000
}

### Validate chat sse
GET http://localhost:{{PORT}}/chat-stream
Content-Type: application/json

{
  "message": "What is quantum physics based quantum?",
  "maxTokenCount": 2000
}

